blank_issues_enabled: false
contact_links:
  - name: Getting Help / Community
    url: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
    about: Please click here to learn about where to ask questions about HAPI FHIR
